name: YumChenmosStupas
favicon: null
layout_spectrum: 0.24868
typography_spectrum: 0.25571
title: Yum Chenmo's Stupas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011aff'
    - '#ff0100'
    - '#dcc100'
    - '#3ef700'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
