name: YumChenmosStupas
favicon: null
layout_spectrum: 0.99736
typography_spectrum: 0.68598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011aff'
    - '#ff0100'
    - '#dcc100'
    - '#3ef700'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.016630412312224507
purpose: []
